return {
  ["workshop-1079538195"]={
    configuration_options={
      beebox=true,
      birdcage=true,
      cartographydesk=true,
      cookpot=true,
      dragonflychest=true,
      dragonflyfurnace=true,
      endtable=true,
      firesuppressor=true,
      icebox=true,
      lightning_rod=true,
      meatrack=true,
      modsupport=false,
      moondial=true,
      mushroom_farm=true,
      mushroom_light=true,
      nightlight=true,
      perdshrine=true,
      pottedfern=true,
      rainometer=true,
      researchlab=true,
      researchlab2=true,
      researchlab3=true,
      researchlab4=true,
      resurrectionstatue=true,
      saltlick=true,
      scarecrow=true,
      sculptingtable=true,
      succulent_potted=true,
      townportal=true,
      treasurechest=true,
      wardrobe=true,
      winterometer=true 
    },
    enabled=true 
  },
  ["workshop-1185229307"]={ configuration_options={  }, enabled=true },
  ["workshop-1301033176"]={ configuration_options={ LANG="simplified" }, enabled=true },
  ["workshop-1530801499"]={
    configuration_options={ Hunger_Cost=1, Ownership=false, Sanity_Cost=1 },
    enabled=true 
  },
  ["workshop-1458450094"]={
    configuration_options={
      [""]=0,
      houndstooth=false,
      log=false,
      mode="fix",
      retrapfix=60,
      retraprandomx=10,
      retraprandomy=120,
      rope=false 
    },
    enabled=true 
  },
  ["workshop-1750657150"]={
    configuration_options={
      amount_of_numbers="low",
      display_mode="straight",
      dmg_only="on",
      number_size="tiny",
      show_beaverness="off",
      show_decimal_points="no",
      show_fueled="off",
      show_hunger="off",
      show_moisture="off",
      show_sanity="off",
      show_work="off",
      size_scale="off" 
    },
    enabled=true 
  },
  ["workshop-1768821433"]={
    configuration_options={ backpack_setting=3, language=2, refresh_time=1 },
    enabled=true 
  },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-661253977"]={
    configuration_options={ amudiao=true, baodiao=1, kong=0, rendiao=2, zbdiao=true },
    enabled=true 
  },
  ["workshop-934638020"]={ configuration_options={  }, enabled=true },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-569043634"]={ configuration_options={  }, enabled=true } 
}
